books_calender/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hello.urls')),
    path('accounts/', include('allauth.urls')),

]

hello/urls.py
from django.urls import path
from . import views

app_name = 'hello'
urlpatterns = [
  path('', views.BooksListView.as_view(), name="index"),
  path('book_search/', views.book_ajax_search, name="book_ajax_search"),
  path('<int:pk>/keyword_list/', views.KeywordsListView.as_view(),
  name="keyword_list"),
  path('keyword/ajax_add/', views.keyword_ajax_add,
  name="keyword_ajax_add"),
  path('keyword/ajax_update/', views.keyword_ajax_update, 
  name="keyword_ajax_update"),
  path('keyword/ajax_delete/', views.keyword_ajax_delete, 
  name="keyword_ajax_delete"),
  path('<int:pk>/send_date/', views.SendDateView.as_view(),
  name="send_date"),
  path('<int:pk>/send_set/', views.SendSetView.as_view(),
  name="send_set"),
  path('<int:id>/send_change/<int:pk>/', views.SendChangeView.as_view(),
  name="send_change"),
  path('<int:id>/send_delete/<int:pk>/', views.SendDeleteView.as_view(),
  name="send_delete"),
  path('<int:pk>/email_list/', views.EmailListView.as_view(),
  name="email_list"),
  path('<int:id>/email_edit/<int:pk>/', views.EmailEditView.as_view(),
  name="email_edit"),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
  """カスタムユーザーモデル"""

  class Meta:
    verbose_name_plural = 'CustomUser'

hello/models.py
from accounts.models import CustomUser
from django.db import models


# Create your models here.

class Keyword(models.Model):
  """登録キーワードモデル"""
  user = models.ForeignKey(CustomUser, verbose_name = 'ユーザー',
  on_delete = models.CASCADE)
  content = models.CharField(max_length = 50, verbose_name = 'キーワード')

  class Meta:
    verbose_name_plural = 'Keyword'


class WhenEmail(models.Model):
  """各ユーザー毎の、何日まえにメールを送るかを登録するモデル"""
  user = models.ForeignKey(CustomUser, unique=True,
  on_delete = models.CASCADE)
  date_email = models.IntegerField(default = 7,
  verbose_name = '何日前に通知しますか？')
  date_reminder = models.IntegerField(blank = True, null = True,
  verbose_name = 'リマインダーを何日前に送りますか？')

  class Meta:
    verbose_name_plural = 'WhenEmail'

class ShowingBooks(models.Model):
  """ページに表示する本をデータベースに貯めるモデル"""
  title = models.CharField(max_length = 50)
  author = models.CharField(max_length = 50)
  publisher = models.CharField(max_length = 50)
  publishing_date = models.DateField(null = True)

  class Meta:
    verbose_name_plural = 'ShowingBooks'

class SendingBooks(models.Model):
  """登録キーワードにヒットした、メールで送る候補の本のモデル"""
  user = models.ForeignKey(CustomUser, on_delete = models.DO_NOTHING)
  title = models.CharField(max_length = 50)
  author = models.CharField(max_length = 50)
  publisher = models.CharField(max_length = 50)
  publishing_date = models.DateField(null = True)
  is_send_1st = models.BooleanField(null = True)
  is_send_2nd = models.BooleanField(null = True)
  is_overlapping = models.BooleanField(default = False)

  class Meta:
    verbose_name_plural = 'SendingBooks'

class EmailLog(models.Model):
  """検索ヒットした本とユーザーへのメール送信履歴モデル"""
  user = models.ForeignKey(CustomUser, on_delete = models.DO_NOTHING)
  title = models.CharField(max_length = 50)
  author = models.CharField(max_length = 50)
  is_email_1st = models.BooleanField(default = False)
  is_email_2nd = models.BooleanField(default = False)
  date_time_1st_email = models.DateTimeField(auto_now_add = True)
  date_time_2nd_email = models.DateTimeField(auto_now = True)

  class Meta:
    verbose_name_plural = 'EmailLog'

hello/forms.py
from django import forms
from .models import WhenEmail
from accounts.models import CustomUser


class WhenEmailAddForm(forms.ModelForm):
  class Meta:
    model = WhenEmail
    fields = ('date_email', 'date_reminder',)
    labels = { 'date_email': '１通目のメール', 'date_reminder': 'リマインダー' }

  def clean(self):
    cleaned_data = super().clean()
    days_1st = cleaned_data.get('date_email')
    days_2nd = cleaned_data.get('date_reminder')

    if days_1st < 0:
      raise forms.ValidationError('１通目のメールの日数は、0以上の整数を入力してください')

    if days_2nd != None and days_2nd < 0:
      raise forms.ValidationError('リマインダー日数は、0以上の整数を入力してください。あるいは空欄のままにすると、リマインダーを送らない設定になります')

    if days_2nd != None and days_1st <= days_2nd:
      raise forms.ValidationError('リマインダー日数は、１通目のメールより後に届くよう、より小さな数字を選んでください')

class EmailEditForm(forms.ModelForm):
  class Meta:
    model = CustomUser
    fields = ('email',)
    labels = { 'email': '新しいメールアドレス' }

  def clean_email(self):
    email = self.cleaned_data['email']
    is_email_another = CustomUser.objects.filter(email = email)
    if not email:
      raise forms.ValidationError('メールアドレスを入力してください')
    if is_email_another:
      raise forms.ValidationError('他のユーザーが既に使用しているメールアドレスです')
    return email

hello/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import HttpResponse

from accounts.models import CustomUser
from allauth.account.models import EmailAddress
from .models import Keyword, WhenEmail, ShowingBooks
from .forms import WhenEmailAddForm, EmailEditForm
import re



# Create your views here.


class BooksListView(generic.ListView):
  model = ShowingBooks
  template_name = 'index.html'

  def get_queryset(self):
    books = ShowingBooks.objects.all()
    return books


def book_ajax_search(request):
  search_word = request.GET.get("search_word")
  search_word = re.sub(r'\s', '', search_word)
  books = ShowingBooks.objects.all()
  hit_books = ''

  if search_word:
    for book in books:
      title_match = search_word in book.title
      author_match = search_word in book.author

      if (title_match and not author_match):
        if not (book.title == '<取得失敗>'):
          hit_books += book.title + ',' + book.author + ',' + \
          book.publisher + ',' + \
          book.publishing_date.strftime('%Y年%m月%d日') + ','

      if (author_match and not title_match):
        if not (book.author == '<取得失敗>'):
          hit_books += book.title + ',' + book.author + ',' + \
          book.publisher + ',' + \
          book.publishing_date.strftime('%Y年%m月%d日') + ','

      if (author_match and title_match):
        if not (book.title == book.author == '<取得失敗>'):
          hit_books += book.title + ',' + book.author + ',' + \
          book.publisher + ',' + \
          book.publishing_date.strftime('%Y年%m月%d日') + ','

  hit_books += search_word

  return HttpResponse(hit_books)

class KeywordsListView(LoginRequiredMixin, generic.ListView):
  model = Keyword
  template_name = 'keyword_list.html'

  def get_queryset(self):
    keywords = Keyword.objects.filter(user = self.request.user)
    return keywords


def keyword_ajax_add(request):
  keyword_content = request.POST.get("keyword_content")
  keyword_content = re.sub(r'\s', '', keyword_content)
  add_obj = Keyword()
  if keyword_content:
    add_obj.user = request.user
    add_obj.content = keyword_content
    add_obj.save()
    id_content = str(add_obj.pk) + ',' + keyword_content
  else:
    id_content = ''

  return HttpResponse(id_content)

def keyword_ajax_update(request):
  keyword_id = request.POST.get("keyword_id")
  keyword_content = request.POST.get("keyword_content")
  keyword_content = re.sub(r'\s', '', keyword_content)
  upd_obj = Keyword.objects.get(id = keyword_id)
  if keyword_content:
    upd_obj.content = keyword_content
    upd_obj.save()
  else:
    upd_obj.delete()

  return HttpResponse(keyword_content)

def keyword_ajax_delete(request):
  keyword_id = request.POST.get("keyword_id")
  del_obj = Keyword.objects.get(id = keyword_id)
  del_obj.delete()
  return HttpResponse(keyword_id)

class SendDateView(LoginRequiredMixin, generic.ListView):
  model = WhenEmail
  template_name = 'send_date.html'

  def get_queryset(self):
    when = WhenEmail.objects.filter(user = self.request.user)
    return when

class SendSetView(LoginRequiredMixin, generic.CreateView):
  model = WhenEmail
  template_name = 'send_set.html'
  form_class = WhenEmailAddForm

  def get_success_url(self):
    return reverse_lazy('hello:send_date',
    kwargs={'pk': self.request.user.pk })

  def form_valid(self, form):
    when = form.save(commit = False)
    when.user = self.request.user
    when.save()
    messages.success(self.request, 'メール通知日を登録しました')
    return super().form_valid(form)

  def form_invalid(self, form):
    messages.error(self.request, 'メール通知日設定に失敗しました')
    return super().form_invalid(form)

class SendChangeView(LoginRequiredMixin, generic.UpdateView):
  model = WhenEmail
  template_name = 'send_change.html'
  form_class = WhenEmailAddForm

  def get_success_url(self):
    return reverse_lazy('hello:send_date',
    kwargs={'pk': self.request.user.pk })

  def form_valid(self, form):
    messages.success(self.request, 'メール通知日を変更しました')
    return super().form_valid(form)

  def form_invalid(self, form):
    messages.error(self.request, 'メール通知日変更に失敗しました')
    return super().form_invalid(form)

class SendDeleteView(LoginRequiredMixin, generic.DeleteView):
  model = WhenEmail
  template_name = 'send_delete.html'
  
  def delete(self, request, *args, **kwargs):
    messages.success(self.request, "メール通知日設定を消去しました")
    return super().delete(request, *args, **kwargs)

  def get_success_url(self):
    return reverse_lazy('hello:send_date',
    kwargs={'pk': self.request.user.pk })

class EmailListView(LoginRequiredMixin, generic.ListView):
  model = CustomUser
  template_name = 'email_list.html'

  def get_queryset(self):
    user_for_email = CustomUser.objects.filter(id = self.request.user.id)
    return user_for_email

class EmailEditView(LoginRequiredMixin, generic.UpdateView):
  model = CustomUser
  template_name = 'email_edit.html'
  form_class = EmailEditForm

  def get_success_url(self):
    return reverse_lazy('hello:index')

  def form_valid(self, form):
    try:
        email_address = EmailAddress.objects.get(user = self.request.user)
        email_address.delete()
    except EmailAddress.DoesNotExist:
        pass

    messages.success(self.request, 'メールアドレスを登録しました')
    return super().form_valid(form)

  def form_invalid(self, form):
    messages.error(self.request, 'メールアドレス更新に失敗しました')
    return super().form_invalid(form)

hello/templates/email_edit.html
{% extends "hello_base.html" %}
{% block title %}メールアドレス編集{% endblock %}

{% block body %}
<div class="email_edit">
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
      <button type="submit">更新</button>
      <a href="{% url 'hello:index' %}">キャンセル</a>
    </div>
  </form>
</div>
{% endblock %}

hello/templates/email_list.html
{% extends "hello_base.html" %}
{% block title %}メールアドレス{% endblock %}

{% block body %}
<div class="email_list">

  {% for emailuser in customuser_list %}
  <div>現在のメールアドレス : {{emailuser.email}}</div>
  <div>
    <a href="{% url 'hello:email_edit' user.id emailuser.pk %}">メールアドレスを変更</a>
  {% endfor %}
    <a href="{% url 'hello:send_date' user.pk %}">メール通知日を確認</a>
  </div>
</div>
{% endblock %}

hello/templates/hello_base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% load static %}
    {% load sass_tags %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% sass_src 'hello/hello_base.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/index.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/keyword_list.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/send_date.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/send_set.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/send_change.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/send_delete.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/email_list.scss' %}">
    <link rel="stylesheet" href="{% sass_src 'hello/email_edit.scss' %}">


    <title>{% block title %}{% endblock %}</title>

  </head>
  <body>
    <div class="content">
      {% if messages %}
        {% for message in messages %}
          <div class="notices">{{message}}</div>
        {% endfor %}
      {% endif %}
      <nav class="header">
        <h1>新刊発売日一覧</h1>
        <div>当サイトでは、いくつかの出版社様から発売の近い本の紹介をしております。ユーザー登録していただければ、検索キーワードに合致する新刊の情報をメールで通知するサービスがございます。</div>
        {% if user.is_authenticated %}
        <p>現在{{ user.username }}様でログインしています。</p>
        <p>検索キーワードの登録は「検索キーワード一覧」ページに、メール通知の設定は「メール通知日設定」にお進みください。</p>
        <ul class="header__menu">
          <li><a href="{% url 'hello:index' %}">本一覧</a></li>
          <li><a href="{% url 'hello:keyword_list' user.pk %}">検索キーワード一覧</a></li>
          <li><a href="{% url 'hello:send_date' user.pk %}">メール通知日設定</a></li>
          <li><a href="{% url 'hello:email_list' user.id %}">メールアドレス編集</a></li>
          <li><a href="{% url 'account_logout' %}">ログアウト</a></li>
        </ul>
        {% else %}
        <p>ログインされていません</p>
        <ul class="header__menu_when_logged_off">
          <li><a href="{% url 'account_signup' %}">新規登録</a></li>
          <li><a href="{% url 'account_login' %}">ログイン</a></li>
        {% endif %}
        </ul>
      </nav>
      {% block body %}
      {% endblock %}
    </div>
  </body>
</html>

hello/templates/index.html
{% extends "hello_base.html" %}
{% block title %}新刊発売日一覧{% endblock %}

{% block body %}
<div class="middle">
  <form id="book-search-field">
    <p>タイトルか著者名で検索ができます</p>
    <input class="book-search-line" type="text" placeholder="検索キーワードを入力" value="">
  </form>
  <div id="book-search-result">

  </div>
  <div class="middle__content">
    <h3>発売日一覧</h3>
    <table>
      <thead>
        <tr>
          <th>タイトル</th>
          <th>著者</th>
          <th>出版社</th>
          <th>発売日</th>
        </tr>
      </thead>
      <tbody>
        {% for book in showingbooks_list %}
          <tr>
            <td>{{book.title}}</td>
            <td>{{book.author}}</td>
            <td>{{book.publisher}}</td>
            <td>{{book.publishing_date}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script type="text/javascript">

function add_result(multi_results, len, search_word){

  var lists = ``

  for (var i = 0; i < len; i++) {
    lists += `<tr>`;
    for (j = 0; j < 4; j++) {
      var one_book = `<td>${multi_results[i][j]}</td>`
      lists += one_book;
    }
    lists += `</tr>`;
  }

  var html = `
  <p>「${search_word}」の検索結果</p>
  <table>
    <thead>
      <tr>
        <th>タイトル</th>
        <th>著者</th>
        <th>出版社</th>
        <th>発売日</th>
      </tr>
    </thead>
    <tbody>`
  html += lists;

  var html_tail = `
    </tbody>
  </table>`

  html += html_tail;

  return html;
}

function add_no_result(search_word){

  var html = `<p>「${search_word}」に一致する結果はありません</p>`

  return html;
}

$("#book-search-field").on("keyup", function() {
    var input = $(".book-search-line").val();
    $.ajax({
      url: "/book_search",
      method: "GET",
      data: {search_word: input},
      dataType: "text",
    })
    .done(function(books) {
      $("#book-search-result").empty();

      var results = books.split(",");
      if (results.length !== 1) {

        var search_word = results.pop();
        
        var len = results.length / 4;
        var multi_results = [];
        var begin = 0;
        for (var i = 0; i < len; i++) {
          multi_results.push(results.slice(begin, begin+4));
          begin += 4;
        }

        var html = add_result(multi_results, len, search_word);
        $("#book-search-result").append(html);

      } else  {
        var html = add_no_result(results[0]);
        $("#book-search-result").append(html);
      }
    })
    .fail(function() {
      alert("通信エラーです。検索結果が表示できません。");
    });
});

</script>
{% endblock %}

hello/templates/keyword_list.html
{% extends "hello_base.html" %}
{% block title %}検索ワードリスト{% endblock %}

{% block body %}
<div class="keyword_list">
  <div class="keyword_description">こちらで検索キーワードを登録した上で、メール通知日設定を行うと、検索ワードに合致する本の発売を、設定した通知日に基づいてメールでお知らせいたします。
  </div>
  <p>現在登録されている検索ワード一覧</p>
  <div class="keywords_board">
    {% for keyword in keyword_list %}
    <div class="keyword_cage{{keyword.pk}}">
      <label class="text-like-a" for="keyword_hidden_checkbox{{keyword.pk}}">{{keyword.content}}</label>
      <input type="checkbox" id="keyword_hidden_checkbox{{keyword.pk}}">
      <ul class="keyword_menu{{keyword.pk}}">
        <li class="keyword_questioning{{keyword.pk}}">「<strong>{{keyword.content}}</strong>」を編集しますか？</li>
        <li>
          <form data-keyword_id="{{keyword.pk}}" class="keyword_update" action="{% url 'hello:keyword_ajax_update' %}" method="POST">
            {% csrf_token %}
            <input class="keyword_next{{keyword.pk}}" type="text" name="keyword_content" value="{{keyword.content}}">
            <input type="hidden" name="keyword_id" value="{{keyword.pk}}">
            <input type="submit" value="更新">
          </form>
        </li>
        <li>
          <form class="keyword_delete" action="{% url 'hello:keyword_ajax_delete' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="keyword_id" value="{{keyword.pk}}">
            <input type="submit" value="削除">
          </form>
        </li>
      </ul>
    </div>
    {% endfor %}
  </div>
  <form class="keyword_add" action="{% url 'hello:keyword_ajax_add' %}" method="POST">
    {% csrf_token %}
    <p>検索キーワードを追加</p>
    <div>
    <input class="keyword_add_line" type="text" name="keyword_content" value="">
    <input type="submit" value="追加">
    </div>
  </form>
  <div class="check_email_send"><a href="{% url 'hello:send_date' user.pk %}">メール通知日を確認</a></div>
</div>

<script type="text/javascript">

$(function() {
  var keyword_ids = [];
  $(".keyword_update").each(function() {
    keyword_ids.push($(this).data('keyword_id'));
  });
  $.each(keyword_ids, function(i, id) {
    $("#keyword_hidden_checkbox" + id).addClass("keyword_hidden_checkbox--active");
    $(".keyword_menu" + id).addClass("keyword_menu--active");
  })
  
});

function buildHTML(id, content){

var html = `<div class="keyword_cage${id}">
                  <label class="text-like-a" for="keyword_hidden_checkbox${id}">${content}</label>
                  <input type="checkbox" class="keyword_hidden_checkbox--active" id="keyword_hidden_checkbox${id}">
                  <ul class="keyword_menu${id} keyword_menu--active">
                    <li class="keyword_questioning${id}">「<strong>${content}</strong>」を編集しますか？</li>
                    <li>
                      <form data-keyword_id="${id}" class="keyword_update" action="{% url 'hello:keyword_ajax_update' %}" method="POST">
                        {% csrf_token %}
                        <input class="keyword_next${id}" type="text" name="keyword_content" value="${content}">
                        <input type="hidden" name="keyword_id" value="${id}">
                        <input type="submit" value="更新">
                      </form>
                    </li>
                    <li>
                      <form class="keyword_delete" action="{% url 'hello:keyword_ajax_delete' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="keyword_id" value="${id}">
                        <input type="submit" value="削除">
                      </form>
                    </li>
                  </ul>
                  </div>`

return html;
}

$(".keyword_add").submit(function(e) {
        e.preventDefault();
        var form = $(this);
        $.ajax({
          url: form.prop("action"),
          method: form.prop("method"),
          data: form.serialize(),
          dataType: "text",
        })
        .done(function(id_content) {
          if (id_content) {
            var id_content_list = id_content.split(",");
            var id = id_content_list[0];
            var content = id_content_list[1];
            var html = buildHTML(id, content);
            $(".keywords_board").append(html);
            $(".keyword_add_line").val('');
          }
        })
        .fail(function() {
          alert('キーワード追加に失敗しました。');
        });
});

$('.keywords_board').on("submit", ".keyword_update", function (e) {
        e.preventDefault();
        var form = $(this);
        var keyword_id = form.data('keyword_id');
        $.ajax({
          url: form.prop("action"),
          method: form.prop("method"),
          data: form.serialize(),
          dataType: "text",
        })
        .done(function(data) {
          if (data) {
            $(".keyword_questioning" + keyword_id)
            .html("「<strong>" + data + "</strong>」を編集しますか？");
            form.parents('.keyword_cage' + keyword_id).find('label')
            .html(data);
          } else {
            form.parents('.keyword_cage' + keyword_id).remove();
          }
        })
        .fail(function() {
          alert('更新に失敗しました。');
        });
});

$('.keywords_board').on("submit", ".keyword_delete", function (e) {
        e.preventDefault();
        var form = $(this);
        $.ajax({
          url: form.prop("action"),
          method: form.prop("method"),
          data: form.serialize(),
          dataType: "text",
        })
        .done(function(data) {
          form.parents('.keyword_cage' + data).remove();
        })
        .fail(function() {
          alert('削除に失敗しました。');
        });
});

  
</script>
{% endblock %}

hello/templates/send_change.html
{% extends "hello_base.html" %}
{% block title %}メール通知日変更{% endblock %}

{% block body %}
<div class="send_change">
  <div>検索ワードに合致した本について、その発売日の何日前にメールで通知して欲しいか入力してください（当日通知して欲しい場合は、0を入力してください）。メールは、１通目と、リマインダーで計２通送れますが、リマインダーの欄は空白のままにすることで、１通目だけを送ることもできます。
  </div>
  <form method="POST">
    {% csrf_token %}
      {{ form.as_p }}
    <div>
    <button type="submit">更新</button>
    <a href="{% url 'hello:send_date' user.pk %}">キャンセル</a>
    </div>
  </form>
</div>

{% endblock %}

hello/templates/send_date.html
{% extends "hello_base.html" %}
{% block title %}メール通知日{% endblock %}

{% block body %}

<div class="send_date">
  <div>ここでは、キーワードに合致する本の発売日の何日前にお知らせメールを送るかを設定できます。</div>
  {% for when in whenemail_list %}
    {% if when.date_email == 0 %}
      <div>検索ワードに合致する本の発売を、発売日<span>当日</span>にお知らせします</div>
    {% else %}
      <div>検索ワードに合致する本の発売を、発売日の<span>{{ when.date_email }}</span>日前から、発売が分かり次第お知らせいたします
      </div>
    {% endif %}
    {% if when.date_reminder != None %}
      {% if when.date_reminder == 0 %}
        <div>リマインダーは発売日<span>当日</span>にお送りします</div>
      {% else %}
        <div>リマインダーは発売の<span>{{ when.date_reminder }}</span>日前から、発売が分かり次第お送りします
        </div>
      {% endif %}
    {% endif %}
    <div><a href="{% url 'hello:send_change' user.id when.pk %}">既存のメール通知日を変更</a></div>
    <div><a href="{% url 'hello:send_delete' user.id when.pk %}">メール通知をしないようにする</a></div>
  {% empty %}
    <div>登録されたメール通知日設定はありません</div>
    <div><a href="{% url 'hello:send_set' user.pk %}">メール通知日を設定</a></div>
  {% endfor %}
</div>
{% endblock %}

hello/templates/send_delete.html
{% extends "hello_base.html" %}
{% block title %}メール通知日消去{% endblock %}

{% block body %}
<div class="send_delete">
  <p>メール通知設定を削除しますか？一旦削除しても、再設定可能です。</p>
  <form method="POST">
    {% csrf_token %}
    <div>
      <button type="submit">削除</button>
      <a href="{% url 'hello:send_date' user.id %}">キャンセル</a>
    </div>
  </form>
</div>
{% endblock %}

hello/templates/send_set.html
{% extends "hello_base.html" %}
{% block title %}メール通知日設定{% endblock %}

{% block body %}
<div class="send_set">
  <div>検索ワードに合致した本について、その発売日の何日前にメールで通知して欲しいか入力してください（当日通知して欲しい場合は、0を入力してください）。メールは、１通目と、リマインダーで計２通送れますが、リマインダーの欄は空白のままにすることで、１通目だけを送ることもできます。
  </div>
  <form method="POST">
    {% csrf_token %}
      {{ form.as_p }}
    <div>
    <button type="submit">登録</button>
    <a href="{% url 'hello:send_date' user.pk %}">キャンセル</a>
    </div>
  </form>
</div>
{% endblock %}